### PR TITLE
docs: 📚 Autocompletion in HTML

### LINKED ISSUE #44: docs: 📚 Autocompletion in HTML
---

**Description**:

As a user, I want to be able to get vscode autocompletion for the components

**Rationale**:

Better DX

### PR DESCRIPTION
**Pull request by schilchSICKAG**
# Pull Request

## 📖 Description

This PR adds information about how to use VSCode autocompletion for projects that are using our components.

### 🎫 Issues

Closes #44.

## 👩‍💻 Reviewer Notes

Just have a look at the new [README.md](https://github.com/SickDesignSystem/synergy/blob/docs/autocompletion-in-HTML/packages/components/README.md#5-add-html-autocompletion-to-vscode-optional) for components

## 📑 Test Plan

- Create a new, empty project (e.g. via `npm init`).
- Install our components package `npm install --save @synergy-design-system/components@main`).
- Proceed like described in the new README.md.
- Create a new file `index.html`
- You should now get autocomplete when typing `<syn` for `syn-button` and `syn-input`

## ✅ Checklist

- [x] I have tested my changes manually.
- [ ] I have added automatic tests for my changes (unit- and visual regression tests).
- [x] I have updated the project documentation to reflect my changes (e.g. CHANGELOG, Storybook, ...).
- [x] I have made sure to follow the projects coding and contribution guides.
- [x] I have made sure that the bundle size has changed appropriately.
- [x] I have validated that there are no accessibility errors.
- [ ] I have used design tokens instead of fix css values

### CODE REVIEW

**Comment by mariohamann** [comment]
I would expect that to see that in Storybook, not in the README.

**Comment by schilchSICKAG** [comment]
> I would expect that to see that in Storybook, not in the README. From my perspective Storybook is the single source of truth how to work with our components. Of course some basic installation might make sense, but I would more link directly to Storybook.

Documentation is also included in Storybook, as seen in https://sickdesignsystem.github.io/synergy/?path=/docs/packages-components--docs. This will be further extended when we split up the documentation of the packages (e.g. Components/Install, Components/Dev, Components/Testing)

**Comment by mariohamann** [comment]
Got it. Can we change the order that the packages are before components?

https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy#sorting-stories

Or would you do that in another ticket?

CleanShot 2023-11-15 at 09 48 35@2x

**Review by mariohamann — DISMISSED** [review]

**Comment by schilchSICKAG** [comment]
> Got it. Can we change the order that the packages are before components?
> 
> https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy#sorting-stories
> 
> Or would you do that in another ticket?
> 
> CleanShot 2023-11-15 at 09 48 35@2x

I would opt to create the whole documentation tickets that we need for the MVP and proceed from there, honestly. I also think we will have much more documentation in Storybook in the future (e.g. adding an Icon overview like we had in the old version, adding color swatches and the like), which would give us some more hirarchy.

**Comment by schilchSICKAG** [comment]
See https://github.com/SickDesignSystem/synergy/issues/140 for a follow up ticket on this.

**Review by klaarseSICKAG — APPROVED** [review]

**Pull request merged**
